spring:
  servlet:
    multipart:
      enabled: true
      # 单个文件的最大限制
      max-file-size: 1000MB
      # 单个请求的总限制（包含所有上传文件）
      max-request-size: 1000MB
  datasource:
    url: jdbc:mysql://localhost:3306/hsi_detection_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 2728885797ghdsx.
    driver-class-name: com.mysql.cj.jdbc.Driver

predict:
  url: ${PREDICT_URL:http://model:5000}

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: org.example.server.domain
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 项目相关配置
file:
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /app/data/upload
  output: /app/data/output
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
